/**
 * Types and interfaces for the Analyst Agent with phase-based workflow
 */

/**
 * Main state for the Analyst Agent, tracks progress through all phases
 */
export interface AnalystState {
  // Input inicial do usuário
  userInput: string
  
  // FASE 1: Intent Extraction
  intent?: {
    objective: string
    technicalTerms: string[]
    clarityScore: number
    category?: string
    ambiguities: string[]
  }
  
  // FASE 2: Context Gathering
  context?: {
    code: RetrievalResult[]
    documentation: RetrievalResult[]
    prevention: RetrievalResult[]
    tasks: RetrievalResult[]
    existingPatterns: Pattern[]
    gaps: string[]
  }
  
  // FASE 3: Questions
  questions: Question[]
  answers: Answer[]
  
  // FASE 4: Design Options
  options: DesignOption[]
  chosenOption?: DesignOption
  
  // FASE 5: Specification
  specification?: string
  
  // Controle de fluxo
  currentPhase: 'intent' | 'context' | 'questions' | 'options' | 'spec' | 'done'
  sessionId: string
  createdAt: Date
}

/**
 * Result from cappy_retrieve_context tool
 */
export interface RetrievalResult {
  content: string
  metadata: {
    source: 'code' | 'documentation' | 'prevention' | 'task'
    filePath?: string
    lineStart?: number
    lineEnd?: number
    type?: string
    category?: string
    relevanceScore?: number
  }
  score: number
}

/**
 * Existing pattern found in codebase
 */
export interface Pattern {
  name: string
  description: string
  examples: Array<{
    file: string
    lines: string
    snippet: string
  }>
  usageCount: number
  category?: string
}

/**
 * Question generated by the agent to fill context gaps
 */
export interface Question {
  id: string
  question: string
  type: 'clarification' | 'technical' | 'design' | 'constraint'
  context: string
  why: string
  options?: string[]
  whatFound?: string
}

/**
 * User answer to a question
 */
export interface Answer {
  questionId: string
  answer: string
  timestamp: Date
}

/**
 * Design option for implementation
 */
export interface DesignOption {
  id: string
  name: string
  summary: string
  description: string
  integration: string
  modifications: string[]
  risks: string[]
  effort: string
  pros: string[]
  cons: string[]
  codeExamples: Array<{
    file: string
    lines: string
    description: string
    snippet?: string
  }>
  preventionRules?: string[]
}

/**
 * Result of phase processing
 */
export type PhaseResult =
  | { type: 'continue' }
  | { type: 'yield'; content: AsyncIterable<string> }
  | { type: 'wait_user'; messageId: string; question?: Question; options?: DesignOption[] }
  | { type: 'done' }
