/**
 * @fileoverview Main orchestrator for planning/sandbox turns.
 * @module application/orchestrator/AgentOrchestrator
 */

import * as crypto from 'crypto';
import type {
  IAgentModeEngine,
  ChatMode,
  IAuditTrailService,
  IPlanningModeEngine,
  ISandboxRuntime,
  UserTurnInput,
} from '../../../shared/types/agent';
import { SessionStore } from '../session/SessionStore';

/**
 * Result of one orchestrated turn.
 */
export interface OrchestratorTurnResult {
  /**
   * Session id used in this turn.
   */
  sessionId: string;
  /**
   * Run id used across all events in this turn.
   */
  runId: string;
  /**
   * Assistant response markdown/text.
   */
  responseText: string;
  /**
   * Final mode used.
   */
  mode: ChatMode;
  /**
   * Optional tool-call timeline generated by Agent mode.
   */
  toolCalls?: Array<{
    tool: string;
    status: 'running' | 'done' | 'error';
    input?: string;
    output?: string;
  }>;
}

/**
 * Coordinates mode engines and updates chat session timeline.
 */
export class AgentOrchestrator {
  private readonly agentMode?: IAgentModeEngine;
  private readonly auditTrail?: IAuditTrailService;

  constructor(
    private readonly sessionStore: SessionStore,
    private readonly planningMode: IPlanningModeEngine,
    private readonly sandboxRuntime: ISandboxRuntime,
    agentModeOrAudit?: IAgentModeEngine | IAuditTrailService,
    auditTrailMaybe?: IAuditTrailService,
  ) {
    if (
      agentModeOrAudit
      && typeof (agentModeOrAudit as IAuditTrailService).appendIfNew === 'function'
      && !auditTrailMaybe
    ) {
      this.auditTrail = agentModeOrAudit as IAuditTrailService;
      this.agentMode = undefined;
      return;
    }
    this.agentMode = agentModeOrAudit as IAgentModeEngine | undefined;
    this.auditTrail = auditTrailMaybe;
  }

  /**
   * Executes one user turn in selected mode.
   */
  async runTurn(
    input: Omit<UserTurnInput, 'sessionId' | 'runId'> & { sessionId?: string; runId?: string; attempt?: number },
  ): Promise<OrchestratorTurnResult> {
    const session = this.sessionStore.getOrCreateSession(input.sessionId, input.mode);
    const runId = input.runId ?? `run-${crypto.randomUUID()}`;
    const attempt = input.attempt ?? 1;
    const turnInput: UserTurnInput = {
      sessionId: session.id,
      runId,
      prompt: input.prompt,
      mode: input.mode,
    };

    await this.auditTrail?.appendIfNew({
      eventType: 'turn.started',
      sessionId: session.id,
      runId,
      actor: 'orchestrator',
      payloadRef: turnInput.mode,
      attempt,
    });

    this.sessionStore.appendMessage(session.id, {
      role: 'user',
      content: input.prompt,
      mode: input.mode,
    });
    await this.auditTrail?.appendIfNew({
      eventType: 'turn.user_appended',
      sessionId: session.id,
      runId,
      actor: 'orchestrator',
      payloadRef: input.mode,
      attempt,
    });

    try {
      let responseText: string;
      let toolCalls: OrchestratorTurnResult['toolCalls'];
      if (turnInput.mode === 'planning') {
        const planning = await this.planningMode.run(turnInput);
        responseText = planning.markdown;
      } else if (turnInput.mode === 'agent' && this.agentMode) {
        const agent = await this.agentMode.run(turnInput);
        responseText = agent.markdown;
        toolCalls = agent.toolCalls;
        for (const toolCall of toolCalls) {
          this.sessionStore.appendMessage(session.id, {
            role: 'tool',
            content: JSON.stringify(toolCall),
            mode: input.mode,
          });
        }
      } else {
        const sandbox = await this.sandboxRuntime.execute(turnInput);
        responseText = sandbox.report;
      }

      this.sessionStore.appendMessage(session.id, {
        role: 'assistant',
        content: responseText,
        mode: input.mode,
      });
      await this.auditTrail?.appendIfNew({
        eventType: 'turn.assistant_appended',
        sessionId: session.id,
        runId,
        actor: 'orchestrator',
        payloadRef: input.mode,
        attempt,
      });
      await this.auditTrail?.appendIfNew({
        eventType: 'turn.completed',
        sessionId: session.id,
        runId,
        actor: 'orchestrator',
        payloadRef: input.mode,
        attempt,
      });

      return {
        sessionId: session.id,
        runId,
        responseText,
        mode: input.mode,
        toolCalls,
      };
    } catch (error) {
      await this.auditTrail?.appendIfNew({
        eventType: 'turn.failed',
        sessionId: session.id,
        runId,
        actor: 'orchestrator',
        payloadRef: input.mode,
        attempt,
        metadata: {
          error: error instanceof Error ? error.message : String(error),
        },
      });
      throw error;
    }
  }

  /**
   * Exposes all sessions for UI sync.
   */
  listSessions() {
    return this.sessionStore.listSessions();
  }
}

