/**
 * CAPPY Template Strings
 * 
 * Default templates for various CAPPY features
 */

export const Templates = {
  /**
   * New task instruction template
   */
  NEW_TASK: `# 🎯 Task: {{title}}

**Category:** {{category}}
**Status:** active
**Created:** {{created}}
{{#if description}}
**Description:** {{description}}
{{/if}}

---

## 📋 Context

{{#if preventionRules}}
### Prevention Rules
{{preventionRules}}
{{/if}}

{{#if relatedTasks}}
### Related Tasks
{{relatedTasks}}
{{/if}}

---

## 📚 Relevant Documentation

{{#if relevantDocs}}
{{relevantDocs}}
{{else}}
No relevant documentation found.
{{/if}}

---

## ✅ Acceptance Criteria

- [ ] Implementation complete
- [ ] Code reviewed
- [ ] Tests added
- [ ] Documentation updated

---

## 📝 Notes

{{#if notes}}
{{notes}}
{{/if}}
`,

  /**
   * Prevention rules XML template
   */
  PREVENTION_RULES_XML: `<?xml version="1.0" encoding="UTF-8"?>
<prevention-rules>
  <rule category="{{category}}" severity="{{severity}}">
    <description>{{description}}</description>
    <pattern>{{pattern}}</pattern>
    <solution>{{solution}}</solution>
  </rule>
</prevention-rules>`,

  /**
   * Config YAML template
   */
  CONFIG_YAML: `version: {{version}}
created: {{created}}
workspace: {{workspace}}

features:
  telemetry: {{telemetry}}
  autoIndex: true
  semanticSearch: true

indexing:
  includePaths:
    - "**/*.{ts,js,tsx,jsx,py,java,go}"
    - "**/*.md"
  excludePaths:
    - "**/node_modules/**"
    - "**/dist/**"
    - "**/.git/**"

ai:
  provider: "openai"
  model: "gpt-4"
  embeddingModel: "text-embedding-3-small"
`,

  /**
   * Stack.md template
   */
  STACK_MD: `# 📚 Project Stack

> Auto-generated by CAPPY on {{created}}

## Technology Stack

### Frontend
- Framework: 
- UI Library: 
- State Management: 

### Backend
- Runtime: 
- Framework: 
- Database: 

### Tools & Libraries
- 

## Project Structure

\`\`\`
{{projectStructure}}
\`\`\`

## Key Patterns

### Architecture

### Design Patterns

## Notes

`,
} as const;

/**
 * Convert value to string safely
 */
function valueToString(value: unknown): string {
  if (value === null || value === undefined) {
    return '';
  }
  if (typeof value === 'string') {
    return value;
  }
  if (typeof value === 'number' || typeof value === 'boolean') {
    return String(value);
  }
  if (Array.isArray(value)) {
    return value.join(', ');
  }
  return JSON.stringify(value);
}

/**
 * Fill template with data
 */
export function fillTemplate(template: string, data: Record<string, unknown>): string {
  let result = template;
  
  // Replace {{variable}}
  for (const [key, value] of Object.entries(data)) {
    const regex = new RegExp(`{{${key}}}`, 'g');
    result = result.replace(regex, valueToString(value));
  }
  
  // Handle {{#if}}...{{/if}}
  result = result.replaceAll(/{{#if\s+(\w+)}}([\s\S]*?){{\/if}}/g, (_match, key, content) => {
    return data[key] ? content : '';
  });
  
  // Handle {{#unless}}...{{/unless}}
  result = result.replaceAll(/{{#unless\s+(\w+)}}([\s\S]*?){{\/unless}}/g, (_match, key, content) => {
    return data[key] ? '' : content;
  });
  
  // Handle {{else}}
  result = result.replaceAll('{{else}}', '');
  
  return result;
}
