# Cappy Configuration
version: "__VERSION__"

cappy:
  initialized_at: "__INITIALIZED_AT__"
  last_updated: "__LAST_UPDATED__"

stack:
  source: ".cappy/stack.md"
  validated: false
  validated_at:


tasks:
  directory: "tasks"
  history_directory: "history"

instructions:
  directory: "instructions"
