/**
 * @fileoverview Plan data models
 * @module codeact/core/plan
 */

/**
 * Individual task in a development plan
 */
export interface PlanTask {
  id: string;
  description: string;
  filesToModify: string[];
  dependencies: string[]; // IDs of tasks that must complete first
  estimatedComplexity: "low" | "medium" | "high";
  technicalNotes?: string;
  position: number; // Order in the plan
}

/**
 * Development plan generated by the agent
 */
export interface Plan {
  id: string;
  sessionId: string;
  goal: string;
  contextUsed: string[]; // Files/entities from knowledge graph
  tasks: PlanTask[];
  createdAt: number;
  version: number;
}

/**
 * Plan version snapshot for history tracking
 */
export interface PlanVersion {
  id: string;
  planId: string;
  snapshot: Plan;
  changeReason: string;
  createdAt: number;
}

/**
 * Helper to create a new plan
 */
export function createPlan(
  sessionId: string,
  goal: string,
  tasks: Omit<PlanTask, "id" | "position">[],
  contextUsed: string[] = []
): Plan {
  return {
    id: `plan-${Date.now()}-${Math.random().toString(36).substring(7)}`,
    sessionId,
    goal,
    contextUsed,
    tasks: tasks.map((task, index) => ({
      ...task,
      id: `task-${index + 1}`,
      position: index + 1,
    })),
    createdAt: Date.now(),
    version: 1,
  };
}

/**
 * Helper to increment plan version
 */
export function incrementPlanVersion(plan: Plan, reason: string): Plan {
  return {
    ...plan,
    version: plan.version + 1,
  };
}

/**
 * Export plan to markdown format
 */
export function planToMarkdown(plan: Plan): string {
  let md = `# Development Plan\n\n`;
  md += `**Goal:** ${plan.goal}\n\n`;
  md += `**Created:** ${new Date(plan.createdAt).toLocaleString()}\n`;
  md += `**Version:** ${plan.version}\n\n`;

  if (plan.contextUsed.length > 0) {
    md += `## Context Used\n\n`;
    plan.contextUsed.forEach((file) => {
      md += `- \`${file}\`\n`;
    });
    md += `\n`;
  }

  md += `## Tasks\n\n`;

  plan.tasks.forEach((task) => {
    md += `### ${task.position}. ${task.description}\n\n`;
    md += `**Complexity:** ${task.estimatedComplexity}\n\n`;

    if (task.filesToModify.length > 0) {
      md += `**Files to modify:**\n`;
      task.filesToModify.forEach((file) => {
        md += `- \`${file}\`\n`;
      });
      md += `\n`;
    }

    if (task.dependencies.length > 0) {
      md += `**Dependencies:** ${task.dependencies.join(", ")}\n\n`;
    }

    if (task.technicalNotes) {
      md += `**Technical notes:**\n${task.technicalNotes}\n\n`;
    }

    md += `---\n\n`;
  });

  return md;
}
