/**
 * @fileoverview Core contracts for Cappy chat agent architecture.
 * @module shared/types/agent
 */

/**
 * Supported chat execution modes.
 */
export type ChatMode = 'planning' | 'agent' | 'sandbox';

/**
 * Role of a message inside a session timeline.
 */
export type ChatMessageRole = 'system' | 'user' | 'assistant' | 'tool';

/**
 * Risk levels used by policy and approval gates.
 */
export type RiskLevel = 'low' | 'medium' | 'high';

/**
 * Generic message persisted in a session timeline.
 */
export interface ChatMessage {
  /**
   * Unique message id.
   */
  id: string;
  /**
   * Message role.
   */
  role: ChatMessageRole;
  /**
   * Message body.
   */
  content: string;
  /**
   * ISO creation timestamp.
   */
  createdAt: string;
  /**
   * Optional mode that produced this message.
   */
  mode?: ChatMode;
}

/**
 * Session aggregate for chat history and state.
 */
export interface ChatSession {
  /**
   * Unique session id.
   */
  id: string;
  /**
   * Friendly session title shown in UI.
   */
  title: string;
  /**
   * Current execution mode.
   */
  mode: ChatMode;
  /**
   * Visual status for filtering and archive flows.
   */
  status: 'active' | 'archived';
  /**
   * Indicates whether the session is pinned.
   */
  pinned: boolean;
  /**
   * Ordered timeline.
   */
  messages: ChatMessage[];
  /**
   * ISO creation timestamp.
   */
  createdAt: string;
  /**
   * ISO update timestamp.
   */
  updatedAt: string;
}

/**
 * Input payload for a user turn.
 */
export interface UserTurnInput {
  /**
   * Target session id.
   */
  sessionId: string;
  /**
   * Correlation run id for end-to-end timeline reconstruction.
   */
  runId: string;
  /**
   * User prompt.
   */
  prompt: string;
  /**
   * Requested mode.
   */
  mode: ChatMode;
}

/**
 * Structured planning result.
 */
export interface PlanningResult {
  /**
   * Main objective interpreted from prompt.
   */
  objective: string;
  /**
   * Assumptions inferred by the engine.
   */
  assumptions: string[];
  /**
   * Proposed implementation steps.
   */
  steps: string[];
  /**
   * Main execution risks.
   */
  risks: string[];
  /**
   * Suggested validation checklist.
   */
  validation: string[];
  /**
   * Markdown rendered output for UI streaming.
   */
  markdown: string;
}

/**
 * Execution output for sandbox mode.
 */
export interface SandboxResult {
  /**
   * Run identifier.
   */
  runId: string;
  /**
   * Folder used by the isolated worktree.
   */
  worktreePath: string;
  /**
   * Executed commands.
   */
  commands: string[];
  /**
   * Captured stdout/stderr summaries.
   */
  logs: string[];
  /**
   * Git diff generated by the run.
   */
  diff: string;
  /**
   * Final status.
   */
  status: 'success' | 'error';
  /**
   * Human readable report.
   */
  report: string;
}

/**
 * Provider-level request for OpenAI-compatible calls.
 */
export interface ProviderChatRequest {
  /**
   * Prompt to send to provider.
   */
  prompt: string;
  /**
   * Optional system instruction.
   */
  systemPrompt?: string;
  /**
   * Optional model override.
   */
  model?: string;
}

/**
 * Provider-level response.
 */
export interface ProviderChatResponse {
  /**
   * Assistant answer text.
   */
  text: string;
  /**
   * Optional provider model used.
   */
  model?: string;
}

/**
 * Configuration for OpenAI-compatible providers.
 */
export interface ProviderSettings {
  /**
   * OpenAI-compatible base url.
   */
  baseUrl: string;
  /**
   * Model name.
   */
  model: string;
  /**
   * API key (optional when using local providers).
   */
  apiKey?: string;
  /**
   * Backend transport selected by the user.
   */
  backend: 'openai' | 'openclaude';
}

/**
 * Common tool call metadata for timeline/audit.
 */
export interface ToolCallRecord {
  /**
   * Tool name.
   */
  tool: string;
  /**
   * Input payload.
   */
  input: unknown;
  /**
   * Output payload.
   */
  output: unknown;
  /**
   * Risk level assigned by policy.
   */
  risk: RiskLevel;
  /**
   * ISO timestamp.
   */
  createdAt: string;
}

/**
 * Request to execute an MCP tool.
 */
export interface McpToolRequest {
  /**
   * MCP server identifier.
   */
  server: string;
  /**
   * Tool name.
   */
  toolName: string;
  /**
   * Tool arguments payload.
   */
  arguments: Record<string, unknown>;
}

/**
 * Allowed actor identities for unified audit events.
 */
export type AuditActor =
  | 'user'
  | 'system'
  | 'orchestrator'
  | 'tool-broker'
  | 'mcp-gateway'
  | 'sandbox-runtime'
  | 'streaming-callback';

/**
 * Unified append-only audit event schema.
 */
export interface AuditEvent {
  /**
   * Deterministic identifier for dedupe/idempotency.
   */
  eventId: string;
  /**
   * Event semantic name.
   */
  eventType: string;
  /**
   * ISO creation timestamp.
   */
  timestamp: string;
  /**
   * Session correlation id.
   */
  sessionId: string;
  /**
   * Run correlation id.
   */
  runId: string;
  /**
   * Producer identity.
   */
  actor: AuditActor;
  /**
   * Reference-safe payload projection.
   */
  payloadRef: string;
  /**
   * Retry attempt number.
   */
  attempt: number;
  /**
   * Optional metadata for diagnostics.
   */
  metadata?: Record<string, unknown>;
}

/**
 * Correlation context required in MCP execution paths.
 */
export interface McpExecutionContext {
  /**
   * Session correlation id.
   */
  sessionId: string;
  /**
   * Run correlation id.
   */
  runId: string;
  /**
   * Origin actor for auditing.
   */
  actor: AuditActor;
  /**
   * Retry attempt number.
   */
  attempt?: number;
}

/**
 * Generic approval request.
 */
export interface ApprovalRequest {
  /**
   * Action description.
   */
  action: string;
  /**
   * Risk level for the action.
   */
  risk: RiskLevel;
  /**
   * Optional command preview.
   */
  command?: string;
}

/**
 * Provider gateway contract.
 */
export interface IProviderGateway {
  /**
   * Loads effective provider settings.
   */
  getSettings(): Promise<ProviderSettings>;
  /**
   * Persists API key securely.
   */
  setApiKey(apiKey: string): Promise<void>;
  /**
   * Performs a lightweight provider connectivity check.
   */
  testConnection(): Promise<{ ok: boolean; message: string }>;
  /**
   * Sends a chat completion request.
   */
  chat(request: ProviderChatRequest): Promise<ProviderChatResponse>;
}

/**
 * Planning mode contract.
 */
export interface IPlanningModeEngine {
  /**
   * Generates a structured plan.
   */
  run(input: UserTurnInput): Promise<PlanningResult>;
}

/**
 * Sandbox runtime contract.
 */
export interface ISandboxRuntime {
  /**
   * Executes a sandbox run.
   */
  execute(input: UserTurnInput): Promise<SandboxResult>;
}

/**
 * MCP gateway contract.
 */
export interface IMcpGateway {
  /**
   * Executes an MCP tool request under policy.
   */
  execute(request: McpToolRequest, context: McpExecutionContext): Promise<unknown>;
}

/**
 * MCP transport adapter contract.
 */
export interface IMcpTransportAdapter {
  /**
   * Executes one MCP tool call on concrete transport.
   */
  execute(request: McpToolRequest, context: McpExecutionContext): Promise<unknown>;
}

/**
 * Append-only audit store contract.
 */
export interface IAuditTrailStore {
  /**
   * Persists one event.
   */
  append(event: AuditEvent): Promise<void>;
  /**
   * Returns all events correlated with one run.
   */
  readByRunId(runId: string): Promise<AuditEvent[]>;
  /**
   * Returns all events correlated with one session.
   */
  readBySessionId(sessionId: string): Promise<AuditEvent[]>;
  /**
   * Flushes pending writes.
   */
  flush(): Promise<void>;
}

/**
 * Audit service contract with idempotent append semantics.
 */
export interface IAuditTrailService {
  /**
   * Persists one event regardless of duplicates.
   */
  append(event: Omit<AuditEvent, 'eventId' | 'timestamp'>): Promise<AuditEvent>;
  /**
   * Persists one event only when not already seen.
   */
  appendIfNew(event: Omit<AuditEvent, 'eventId' | 'timestamp'>): Promise<AuditEvent | null>;
  /**
   * Reads run timeline in chronological order.
   */
  getRunTimeline(runId: string): Promise<AuditEvent[]>;
}

/**
 * Generic approval gate contract.
 */
export interface IApprovalGate {
  /**
   * Requests explicit user approval.
   */
  requestApproval(request: ApprovalRequest): Promise<boolean>;
}

/**
 * OpenClaude adapter contract (external process integration).
 */
export interface IOpenClaudeAdapter {
  /**
   * Checks if adapter is operational.
   */
  isAvailable(): Promise<boolean>;
  /**
   * Sends prompt through OpenClaude and receives final text.
   */
  send(prompt: string): Promise<string>;
}

