/**
 * One tool invocation requested by the model.
 */
export interface ToolCall {
  id: string;
  name: string;
  arguments: Record<string, unknown>;
}

/**
 * Image attachment sent with a message (base64 data URL).
 */
export interface ImageAttachment {
  dataUrl: string;
  mimeType: string;
}

/**
 * Compact file diff for Write/Edit tool results (host-computed).
 */
export interface FileDiffPayload {
  path: string;
  additions: number;
  deletions: number;
  hunks: Array<{
    lines: Array<{
      type: "context" | "add" | "del";
      text: string;
    }>;
  }>;
}

/**
 * Message model shared by the webview chat UI and bridge payloads.
 */
export interface Message {
  role: "user" | "assistant" | "tool";
  content: string;
  tool_call_id?: string;
  tool_calls?: ToolCall[];
  images?: ImageAttachment[];
  /** Rich diff card when a file was written or edited. */
  fileDiff?: FileDiffPayload;
}

/**
 * MCP server endpoint configuration.
 */
export interface McpServerConfig {
  name: string;
  url: string;
}

/**
 * MCP tool metadata displayed in the webview.
 */
export interface McpTool {
  serverName: string;
  name: string;
  description: string;
}

/**
 * Modo do input: Plain (só texto), Agent (tools + MCP), Ask (leitura/pesquisa).
 */
export type ChatUiMode = "plain" | "agent" | "ask";

/**
 * Cappy runtime configuration payload.
 */
export type ActiveAgent = "coder" | "planner" | "reviewer" | "strategist" | "tdd" | "sdd";

/**
 * Cappy runtime configuration payload.
 */
export interface CappyConfig {
  openrouter: {
    apiKey: string;
    model: string;
    visionModel: string;
    /** Janela de contexto (tokens) — anel de contexto e orçamento no host. */
    contextWindowTokens?: number;
    reservedOutputTokens?: number;
  };
  agent: {
    activeAgent: ActiveAgent;
    systemPrompt: string;
    maxIterations: number;
  };
  mcp: {
    servers: McpServerConfig[];
  };
}

/**
 * Estimativa de uso de contexto enviada pelo host (alinhada ao orçamento OpenRouter / compactação).
 */
export interface ContextUsageSnapshot {
  usedTokens: number;
  limitTokens: number;
  effectiveInputBudgetTokens: number;
  didTrimForApi: boolean;
  droppedMessageCount: number;
}

/** Lifecycle status of a single pipeline stage in the UI. */
export type PipelineStageStatus = "pending" | "running" | "done" | "awaiting-approval";

/** Minimal stage descriptor mirrored from the host pipeline events. */
export interface PipelineStageInfo {
  id: string;
  name: string;
  status: PipelineStageStatus;
  requiresApproval?: boolean;
}

/** Full pipeline UI state — derived from pipeline:* bridge events. */
export interface PipelineUiState {
  id: string;
  name: string;
  stages: PipelineStageInfo[];
  currentStageIndex: number;
  /** true while awaiting pipeline:advance (requiresApproval gate). */
  awaitingApproval: boolean;
}

/** Brief template descriptor returned by pipeline:templates. */
export interface PipelineTemplate {
  id: string;
  name: string;
  stageCount: number;
}

// ── Planner / Spec ─────────────────────────────────────────────────────────

export type PlanStatus = "draft" | "waiting_approval" | "approved" | "in_execution" | "failed";

/** A spec.md contract generated by the Planner agent. */
export interface Plan {
  id: string;
  specMd: string;
  status: PlanStatus;
  createdAt: string;
}
